Repository HackSquadDev/discord-js, pull requests merged in 2022-10, with the labels that each got.

#1 Made The ReadMe
  README.md
Labels: documentation, enhancement

#12 docs: added CODE OF CONDUCT 🛠
  CODE_OF_CONDUCT.md
Labels: documentation

#19 feat: added pre-commit and fixed lint 🛠
  .github/ISSUE_TEMPLATE/custom.md
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierignore
  yarn.lock
Labels: enhancement

#18 refactor: remove unnecessary codes, embed styling
  src/commands/General/ping.ts
  src/commands/Hacksquad/team.ts
  src/commands/Novu/contributor.ts
Labels: enhancement

#20 docs: updated and added issue templates
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/other.yml
  .github/ISSUE_TEMPLATE/support.yml
Labels: documentation, enhancement
